import { combineReducers } from 'redux';
import {
    desertForm, miniCoolersForm, otherAirCoolersForm, portableCoolersForm, towerCoolersForm, windowCoolersForm, airIonizersForm, carAirPurifierForm,
    charcoalAirPurifierForm, electroAirPurifierForm, hepaAirPurifierForm, otherAirPurifierForm, portableAirPurifierForm, ulpaAirPurifierForm,
    otherDehumidifiersForm, otherDeodorisersForm, blowerFansForm, boxFansForm, ceilingFansForm, clipFansForm, drumFansForm, exhaustFansForm, floorFansForm,
    otherFansForm, pedestalFansForm, personalFansForm, tableFansForm, towerFansForm, vortexActionFansForm, wallMountedFansForm, windowFansForm,
    otherHumidifierForm, singleRoomHumidifierForm, wholeHouseHumidifierForm, otherHeatNCoolingForm, airPuriPartNAccessForm, dehumidPartNAccessForm,
    evaCoolerPartNAccessForm, fanPartNAccessForm, heaterPartNAccessForm, humidiPartNAccessForm, replaceBelthumidiForm, otherPartNAccessForm, electricHeatersForm,
    fanHeatersForm, halogenHeatersForm, heatConvertorsHeatersForm, keroseneSpaceHeatersHeatersForm, naturalgasSpaceHeatersForm, otherRoomHeatersForm,
    propaneSpaceHeatersForm, immersionRodsForm, storageWaterHeatersForm, instantWaterHeatersForm
} from './AddProductFormShow';

const rootReducer = combineReducers({
    desertForm,
    miniCoolersForm,
    otherAirCoolersForm,
    portableCoolersForm,
    towerCoolersForm,
    windowCoolersForm,
    airIonizersForm,
    carAirPurifierForm,
    charcoalAirPurifierForm,
    electroAirPurifierForm,
    hepaAirPurifierForm,
    otherAirPurifierForm,
    portableAirPurifierForm,
    ulpaAirPurifierForm,
    otherDehumidifiersForm,
    otherDeodorisersForm,
    blowerFansForm,
    boxFansForm,
    ceilingFansForm,
    clipFansForm,
    drumFansForm,
    exhaustFansForm,
    floorFansForm,
    otherFansForm,
    pedestalFansForm,
    personalFansForm,
    tableFansForm,
    towerFansForm,
    vortexActionFansForm,
    wallMountedFansForm,
    windowFansForm,
    otherHumidifierForm,
    singleRoomHumidifierForm,
    wholeHouseHumidifierForm,
    otherHeatNCoolingForm,
    airPuriPartNAccessForm,
    dehumidPartNAccessForm,
    evaCoolerPartNAccessForm,
    fanPartNAccessForm,
    heaterPartNAccessForm,
    humidiPartNAccessForm,
    replaceBelthumidiForm,
    otherPartNAccessForm,
    electricHeatersForm,
    fanHeatersForm,
    halogenHeatersForm,
    heatConvertorsHeatersForm,
    keroseneSpaceHeatersHeatersForm,
    naturalgasSpaceHeatersForm,
    otherRoomHeatersForm,
    propaneSpaceHeatersForm,
    immersionRodsForm,
    storageWaterHeatersForm,
    instantWaterHeatersForm

});

export default rootReducer;